### ISSUE TITLE
「(配列変数)に(配列)を連結する」が動作しない

### ISSUE THREAD

**Issue by newmomizi** [watayan/PyPEN#3]
a=[0,1,2,3,4,5]
aに6を追加する
aに[7,8]を連結する

これはPyPENの[文法マニュアル](https://watayan.net/prog/PyPEN/manual/syntax.html)から引っ張ってきたものです。
これを実行すると、aが[0,1,2,3,4,5,6,7,8]になると私は考えていましたが、実際に実行すると以下のエラーが発生して強制終了してしまいます。

実行時エラーです
3行目:配列でない値を連結することはできません

※実行環境: https://watayan.net/prog/PyPEN/

**Comment by watayan** [comment]
issueありがとうございます。連結うまくいってないですね。見直してみます。

**Comment by watayan** [comment]
連結のところで，連結する方の配列の値を処理するところが抜けていたようです。処理を追加しましたのでご確認ください。

**Comment by newmomizi** [comment]
正しく動作することを確認しました。ありがとうございます
